version: '3.8'
services:
  db:
    container_name: liredditpostgres_container
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: lireddit
    ports:
      - "5432:5432"
    volumes: 
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local
